=== SiarheiKarach/XMLProject/TouristVoucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.karach.com/tourist-voucher"
            targetNamespace="http://www.karach.com/tourist-voucher"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

  <xsd:complexType name="HotelCharacteristicsType">
    <xsd:sequence>
      <xsd:element name="Stars" type="xsd:integer"/>
      <xsd:element name="Food" type="xsd:string"/>
      <xsd:element name="RoomType" type="RoomType"/>
      <xsd:element name="Amenities" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="RoomType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="SINGLE"/>
      <xsd:enumeration value="DOUBLE"/>

    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="TouristVoucherType">
    <xsd:sequence>
      <xsd:element name="Type" type="xsd:string"/>
      <xsd:element name="Country" type="xsd:string"/>
      <xsd:element name="MinDays" type="xsd:integer"/>
      <xsd:element name="MaxDays" type="xsd:integer"/>
      <xsd:element name="Transport" type="xsd:string"/>
      <xsd:element name="HotelCharacteristics" type="HotelCharacteristicsType"/>
      <xsd:element name="Cost" type="xsd:decimal"/>
      <xsd:element name="StartDate" type="xsd:dateTime"/>
    </xsd:sequence>
    <xsd:attribute name="ID" type="xsd:integer" use="required"/>
    <xsd:attribute name="currency" type="xsd:string" default="USD"/>
  </xsd:complexType>

  <xsd:element name="TouristVouchers">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="TouristVoucher" type="TouristVoucherType" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== SiarheiKarach/XMLProject/TouristVoucher.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TouristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.karach.com/tourist-voucher TouristVoucher.xsd" xmlns="http://www.karach.com/tourist-voucher">
    <TouristVoucher ID="379" currency="EUR">
        <Type>vacation</Type>
        <Country>Spain</Country>
        <MinDays>7</MinDays>
        <MaxDays>8</MaxDays>
        <Transport>Plane</Transport>
        <HotelCharacteristics>
            <Stars>5</Stars>
            <Food>All Inclusive</Food>
            <RoomType>DOUBLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>5000.0</Cost>
        <StartDate>2023-11-20T19:47:15.006254200Z</StartDate>
    </TouristVoucher>
    <TouristVoucher ID="830" currency="EUR">
        <Type>excursion</Type>
        <Country>Poland</Country>
        <MinDays>2</MinDays>
        <MaxDays>3</MaxDays>
        <Transport>Bus</Transport>
        <HotelCharacteristics>
            <Stars>2</Stars>
            <Food>BB</Food>
            <RoomType>SINGLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>500.0</Cost>
        <StartDate>2023-11-20T19:47:15.014232300Z</StartDate>
    </TouristVoucher>
    <TouristVoucher ID="930" currency="USD">
        <Type>weekend</Type>
        <Country>Spain</Country>
        <MinDays>7</MinDays>
        <MaxDays>14</MaxDays>
        <Transport>Plane</Transport>
        <HotelCharacteristics>
            <Stars>4</Stars>
            <Food>HB</Food>
            <RoomType>DOUBLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>3000.0</Cost>
        <StartDate>2023-11-20T19:47:15.014232300Z</StartDate>
    </TouristVoucher>
    <TouristVoucher ID="258" currency="ILS">
        <Type>pilgrimage</Type>
        <Country>Israel</Country>
        <MinDays>14</MinDays>
        <MaxDays>21</MaxDays>
        <Transport>Diverse</Transport>
        <HotelCharacteristics>
            <Stars>3</Stars>
            <Food>All Inclusive</Food>
            <RoomType>DOUBLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>10000.0</Cost>
        <StartDate>2023-11-20T19:47:15.014232300Z</StartDate>
    </TouristVoucher>
</TouristVouchers>
