=== SiarheiKarach/XMLProject/src/main/resources/TouristVoucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.karach.com/tourist-voucher"
           xmlns="http://www.karach.com/tourist-voucher"
           elementFormDefault="qualified">

    <xs:simpleType name="ID">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="DateTime">
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>

    <xs:simpleType name="RoomType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SINGLE"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="TRIPLE"/>
            <xs:enumeration value="QUAD"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Stars">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ONE"/>
            <xs:enumeration value="TWO"/>
            <xs:enumeration value="THREE"/>
            <xs:enumeration value="FOUR"/>
            <xs:enumeration value="FIVE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Food">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AL"/>
            <xs:enumeration value="BB"/>
            <xs:enumeration value="HB"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Transport">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PLANE"/>
            <xs:enumeration value="BUS"/>
            <xs:enumeration value="BOAT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="(VACATION|EXCURSION|WEEKEND|PILGRIMAGE)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="TouristVouchers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TouristVoucher" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Type" type="Type"/>
                            <xs:element name="Country" type="xs:string"/>
                            <xs:element name="MinDays" type="xs:integer"/>
                            <xs:element name="MaxDays" type="xs:integer"/>
                            <xs:element name="Transport" type="xs:string"/>
                            <xs:element name="HotelCharacteristics">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Stars" type="Stars"/>
                                        <xs:element name="Food" type="Food"/>
                                        <xs:element name="RoomType" type="RoomType"/>
                                        <xs:element name="Amenities" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Cost" type="xs:decimal"/>
                            <xs:element name="StartDate" type="xs:dateTime"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="ID" use="required"/>
                        <xs:attribute name="currency" type="xs:string" use="optional" default="USD"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SiarheiKarach/XMLProject/src/main/resources/TouristVoucher.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TouristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.karach.com/tourist-voucher TouristVoucher.xsd" xmlns="http://www.karach.com/tourist-voucher">
    <TouristVoucher currency="EUR" id="22">
        <Type>VACATION</Type>
        <Country>Spain</Country>
        <MinDays>7</MinDays>
        <MaxDays>8</MaxDays>
        <Transport>PLANE</Transport>
        <HotelCharacteristics>
            <Stars>FIVE</Stars>
            <Food>AL</Food>
            <RoomType>DOUBLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>5000.0</Cost>
        <StartDate>2023-12-02T20:55:13.543369300Z</StartDate>
    </TouristVoucher>
    <TouristVoucher currency="EUR" id="839">
        <Type>EXCURSION</Type>
        <Country>Poland</Country>
        <MinDays>2</MinDays>
        <MaxDays>3</MaxDays>
        <Transport>BUS</Transport>
        <HotelCharacteristics>
            <Stars>TWO</Stars>
            <Food>BB</Food>
            <RoomType>SINGLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>500.0</Cost>
        <StartDate>2023-12-02T20:55:13.553341900Z</StartDate>
    </TouristVoucher>
    <TouristVoucher currency="USD" id="313">
        <Type>WEEKEND</Type>
        <Country>Spain</Country>
        <MinDays>7</MinDays>
        <MaxDays>14</MaxDays>
        <Transport>PLANE</Transport>
        <HotelCharacteristics>
            <Stars>FOUR</Stars>
            <Food>HB</Food>
            <RoomType>TRIPLE</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>3000.0</Cost>
        <StartDate>2023-12-02T20:55:13.553341900Z</StartDate>
    </TouristVoucher>
    <TouristVoucher currency="ILS" id="767">
        <Type>PILGRIMAGE</Type>
        <Country>Israel</Country>
        <MinDays>14</MinDays>
        <MaxDays>21</MaxDays>
        <Transport>BOAT</Transport>
        <HotelCharacteristics>
            <Stars>THREE</Stars>
            <Food>BB</Food>
            <RoomType>QUAD</RoomType>
            <Amenities>included</Amenities>
        </HotelCharacteristics>
        <Cost>10000.0</Cost>
        <StartDate>2023-12-02T20:55:13.553341900Z</StartDate>
    </TouristVoucher>
</TouristVouchers>
